// Rebuilds js/landing-multiverse-data.js from the Set 13 demo session
// (app/defaults/demos/set13_example2.dojo.json.gz): every bookmark (name, stats,
// recap, card sections, parent, timestamp, which line is active) plus the cards
// it uses, with the same Ravensburger thumbnail URLs the app reads from its card
// database. The landing page never loads the 9 MB database itself.
//
//   node tools/landing-data.mjs                 fetch the card database
//   node tools/landing-data.mjs --cards a.json  use a local copy of it
//   node tools/landing-data.mjs --check         exit 1 if the file is out of date
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DEMO = join(ROOT, 'app/defaults/demos/set13_example2.dojo.json.gz');
const OUT = join(ROOT, 'js/landing-multiverse-data.js');
// The app's card database (app/index.html loads the same URL).
const CARDS_URL = 'https://cdn.jsdelivr.net/gh/heavenideas/similcana@main/database/allCards.json';

const args = process.argv.slice(2);
const opt = (name) => { const i = args.indexOf(name); return i === -1 ? null : args[i + 1]; };
const check = args.includes('--check');

async function loadCards() {
    const local = opt('--cards');
    if (local) return JSON.parse(readFileSync(local, 'utf8'));
    const res = await fetch(CARDS_URL);
    if (!res.ok) throw new Error(`card database: HTTP ${res.status}`);
    return res.json();
}

export async function buildLandingData(cardDb) {
    const session = JSON.parse(gunzipSync(readFileSync(DEMO)).toString('utf8'));
    const data = session.data;
    const marks = data.bookmarks;
    const byId = Object.fromEntries(marks.map(b => [b.id, b]));
    const activeId = data.currentState.activeBookmarkId;

    // The line you're on: the active node and everything above it.
    const main = new Set();
    for (let b = byId[activeId]; b; b = byId[b.parentId]) main.add(b.id);

    // Same rule as App.bookmarkPlayerIndex(): playerIdx, else the node colour.
    const playerOf = (b) => {
        if (b.playerIdx === 0 || b.playerIdx === 1) return b.playerIdx + 1;
        if (b.color === 'var(--p1)' || /^#a86b32$/i.test(b.color || '')) return 1;
        if (b.color === 'var(--p2)' || /^#3f2e70$/i.test(b.color || '')) return 2;
        return null;
    };

    const used = new Set();
    const nodes = marks.map(b => {
        const m = /Turn (\d+) \| P1: (\d+) - P2: (\d+)/.exec(b.stats || '');
        const sections = {};
        Object.entries(b.sections || { played: b.cardsPlayedData || [] }).forEach(([k, list]) => {
            if (!Array.isArray(list) || !list.length) return;
            sections[k] = list;
            list.forEach(e => used.add(e && typeof e === 'object' ? e.id : e));
        });
        return {
            id: b.id,
            parent: b.parentId && byId[b.parentId] ? b.parentId : null,
            name: b.name,
            stats: b.stats,
            turn: m ? Number(m[1]) : null,
            lore: m ? [Number(m[2]), Number(m[3])] : [0, 0],
            player: playerOf(b),
            comment: b.comment || '',
            ts: b.timestamp,
            main: main.has(b.id),
            active: b.id === activeId,
            sections
        };
    });

    const db = {};
    (cardDb.cards || cardDb).forEach(c => { db[c.id] = c; });
    const cards = {};
    [...used].sort((a, b) => a - b).forEach(id => {
        const c = db[id];
        if (!c) return;
        const images = c.images || {};
        cards[id] = { name: c.fullName || c.name, ink: c.color, cost: c.cost, thumb: images.thumbnail || images.full || '' };
    });

    const active = byId[activeId];
    const turnKey = `${data.currentState.turn}-${data.currentState.activePlayer}`;
    const out = {
        title: session.title.replace(/^Set \d+ example:\s*/, ''),
        inks: session.summary.inks,
        turnNote: (data.currentState.turnComments || {})[turnKey] || '',
        nodes,
        cards
    };
    if (!active) throw new Error('the demo has no active node');
    return '// Snapshot of app/defaults/demos/set13_example2.dojo.json.gz for the landing page:\n' +
        `// the bookmark tree (names, stats, recaps, card sections) plus the ${Object.keys(cards).length} cards it uses,\n` +
        '// with the same Ravensburger thumbnail URLs the app reads from its card database.\n' +
        '// Generated by tools/landing-data.mjs. Do not edit by hand.\n' +
        `window.MV_DATA = ${JSON.stringify(out)};\n`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
    const text = await buildLandingData(await loadCards());
    const old = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (check) {
        if (old !== text) { console.error('js/landing-multiverse-data.js is out of date: run node tools/landing-data.mjs'); process.exit(1); }
        console.log('js/landing-multiverse-data.js is up to date');
    } else if (old === text) {
        console.log('js/landing-multiverse-data.js: no change');
    } else {
        writeFileSync(OUT, text);
        console.log('wrote js/landing-multiverse-data.js');
    }
}
